### PR TITLE
1 name in root: Nataly

### PR DESCRIPTION
**Pull request by trypsynth**
### What are you correcting?

* Nataly.

### What is your source for this pronunciation?

https://www.youtube.com/watch?v=YZIKdpVPw8c

### Have you checked multiple sources to ensure that the original pronunciation is not simply less common?

Yes

### CODE REVIEW

**Comment by Mohamed00** [comment]
Why are you using ‵[n1AtUli]? Can't help but feel that that really doesn't sound right at all. I feel like ‵[n1Atxli] would be more appropriate.

**Comment by trypsynth** [comment]
Hmm, that sounds the exact same to me at my speech rate, but if it sounds better to you and the same to me, its a win-win :) gone ahead and fixed it.

**Comment by Mohamed00** [comment]
Yeah, I can hear the difference. The phoneme you previously used is more appropriate for words like book, look and rook. The x phoneme is used for words like alone, material, sofa and other words with an a sound, such as this one. It's also consistent with Natalie.

**Comment by trypsynth** [comment]
Aha, gotcha. Thanks for letting me know :)

**Pull request merged**
