### PR TITLE
1 word in root: Lurid

### PR DESCRIPTION
**Pull request by trypsynth**
Worth noting that I couldn't get this one exactly how I wanted it. Its pretty close, but I spent about 45 minutes messing with the ID and couldn't get it quite right, at least not to my ear. Suggestions definitely welcome on this one, because maybe I'm just being picky, or missing something obvious.
https://dictionary.cambridge.org/us/pronunciation/english/lurid

### CODE REVIEW

**Comment by Mohamed00** [comment]
That SPR sounds really off to me honestly. Perhaps try `[l1UrXd]? Kind of not sure, though... the original pronunciation seems a bit like a dialectal variation, but I guess I could add it...

**Comment by trypsynth** [comment]
Hmm, interesting, `[l1UrXd] sounds pretty off to me. Do you have a source that says it like Eloquence originally does? If so I'll go ahead and close this.

**Comment by Mohamed00** [comment]
I looked this word up more, and I can't seem to find one, so will add this, though it's very much on the open to reconsider pile. I still don't quite agree with the SPR, though. The best way I can describe it is that that ID part of it makes that section of the word sound too emphasized, a bit like using `[kxn1EktId] vs `[kxn1EktXd].

**Comment by trypsynth** [comment]
I totally agree actually, hence why I said I wasn't entirely sure. `[l1UrXd] didn't make the ER sound emphasized enough to my ear though.

**Comment by Mohamed00** [comment]
I think that for now `[l1RXd] might be the best SPR to use here. Perhaps it's a speaking rate thing?

**Comment by trypsynth** [comment]
Ah, perhaps you're right. I slowed my Eloquence down from rate boost 55 to around 30, and it sounds great :) I just pushed the change.

**Pull request merged**
