### PR TITLE
1 word in root: Dictatorship

### PR DESCRIPTION
**Pull request by trypsynth**
### What are you correcting?

* Dictatorship

### What is your source for this pronunciation?

1. https://www.youtube.com/watch?v=KAQo87i4doQ
2. https://www.youtube.com/watch?v=1jBi-SdXqD4
3. https://howjsay.com/how-to-pronounce-dictatorship

### Have you checked multiple sources to ensure that the original pronunciation is not simply less common?

Yes, I provided links above. Also, this now alines with how IBMTTS says dictator.

### Is this a compound word? If so, please provide several examples of real world usage.

Yes. Its a form of government, in which a single person (a dictator) rules. https://www.merriam-webster.com/dictionary/dictatorship

### CODE REVIEW

**Comment by Mohamed00** [comment]
I don't think I want to add this honestly. I was able to find sources that list the original as a second pronunciation. IBMTTS can read the IPA in these sources.
https://www.dictionary.com/browse/dictatorship
https://en.wiktionary.org/wiki/dictatorship
Oxford Languages, which powers Google's definitions, also seems to list the original as a second pronunciation, though it's not spoken. Also not sure what you mean by "alines with how IBMTTS says dictator." It seems that the original pronunciation would be consistent in this case. IBMTTS says `[d1Ik2tetR], not `[dIkt1etR].

**Comment by trypsynth** [comment]
How do I read that IPA? It just shows as a bunch of weird foreign character garbage, at least to macOS VoiceOver with Eloquence. I've yet to find it spoken that way. With both the links you sent, the SPR I added seems to be correct.

**Comment by Mohamed00** [comment]
It can be read with IBMTTS on Windows if it's in an SSML block, an the text encoding is UTF-8. No idea about MacOS.

**Comment by trypsynth** [comment]
Even when reading on Windows, I hear: / d?kˈte? t?r???p. Do I have to toggle a setting? The phonetic pronunciation seems correct with what I put (dik-tey-ter-ship).

Testing this on Windows and I get slightly different results, but at least on the Mac, it says dictator almost exactly how it this PR says dictatorship, just without the ship. That's probably not the best mode of test, namely because there's no official way to edit Eloquence dictionaries on the Mac, I'm using a huge hack.

**Comment by Mohamed00** [comment]
Change 		else: self.currentEncoding = "mbcs" to 		else: self.currentEncoding = "utf8", and restart. Then read the IPA with SSML, like so: `<speak> <phoneme alphabet="ipa" ph="dɪkˈteɪtərˌʃɪp ˈdɪkteɪ">`

**Comment by Mohamed00** [comment]
Also I'm referring to `*actual*` IBMTTS 6.7 or newer, not Eloquence.

**Comment by trypsynth** [comment]
Ah, okay I see. I don't think I'm using actual IBMECI with this add-on, rather I think like, Eloquence 5?  I'll try to track down IBMTTS 6.7 for later PRs. Thanks

Also, would you say IPAs are more credible than phonetic pronunciations and recordings?

**Comment by Mohamed00** [comment]
Yeah, pretty much nobody uses actual ibmeci, heh. I use it for various reasons, this being one of them. I think recordings an IPA pronunciations should both be considered, especially since some dictionaries note second pronunciations in IPA form, but may not necessarily speak them. However, ibmeci doesn't seem to like IPA from Oxford Languages and Webster for some reason, though pronunciations can be inferred if you read character by character, due to the way those dictionaries format their IPA. It handles IPA pronunciations from dictionary.com and Wikipedia just fine, though.

**Pull request closed without merging**
