### PR TITLE
One word in root: Refill

### PR DESCRIPTION
**Pull request by trypsynth**
https://www.youtube.com/watch?v=eqs5KFIvsbM

### CODE REVIEW

**Comment by Mohamed00** [comment]
Hi, I'm a bit reluctant to change this one. The pronunciation may be a bit off, but it's tied to a rule. It has two different forms of the word, both the verb, but there's also a second form, used in phrases like he will refill the proscription, and adding it to the root dictionary will kill that.

**Comment by trypsynth** [comment]
I'm not sure I get that one. He will refill the proscription with the entry sounds fine to my ear. What breaks?

**Comment by Mohamed00** [comment]
There are two meanings of refill, and they're pronounced differently, 
and by default, it tries to distinguish between the two. Compare these 
two sentences. I have a refill. I will refill it. Adding this entry to 
the root dictionary will kill that. Since both meanings of the word are 
pronounced differently, I'm leaning towards letting it distinguish 
between the two rather than forcing one or the other. Sources: 
https://www.merriam-webster.com/dictionary/refill
https://www.dictionary.com/browse/refill

https://dictionary.cambridge.org/us/dictionary/english/refill

**Comment by trypsynth** [comment]
Aha, I see. I'll go ahead and close this, then.

**Pull request closed without merging**
