### PR TITLE
Added arcing

### PR DESCRIPTION
**Pull request by kara-louise**
### What are you correcting?
arcing
### What is your source for this pronunciation?
Collins dictionary - derivative form of arc
### What additional sources have you checked to make sure that the original pronunciation is not simply less common?
none
### Is this a compound word? If so, please provide several examples of real world usage.
no

### CODE REVIEW

**Comment by Mohamed00** [comment]
Why did you choose to put this in main rather than root? That dictionary is case-sensitive so you've have to add several variations.

**Comment by Mohamed00** [comment]
Also you might want to put a newline at the end of the files for cleaner diffs, so Git won't treat them as one insertion and one deletion all the time.

**Comment by kara-louise** [comment]
I tried replying this via e-mail but it didn't work apparently.
Take 2.
Ah, of course. , I did originally put it in root, then wasn't sure, so put it in main instead.
Stick it back in root.

**Comment by Mohamed00** [comment]
Added. Here are some tips for next time.
* Make sure you always put a new line at the end of a file. Git will always complain if a new line doesn't exist, and without a new line, your diffs will always appear as one insertion and one deletion, rather than just one insertion.
* Make sure to modify the IBM dictionary. While IBM has many fixes that aren't in Eloquence, in terms of words, they will generally mispronounce the same things. If you don't have IBMTTS, that's fine, I'll tell you if it says something correctly so you can remove it.

**Pull request merged**
