### PR TITLE
Root: agender,androgyne,bigender,xenogender,xenogenders,transmasc,transfeminine,transfem,genderfuck,genderpunk

### PR DESCRIPTION
**Pull request by ns-studios**

### CODE REVIEW

**Comment by Mohamed00** [comment]
Why is transmasculine in here? It's in the dictionary already. Can you provide sources if you think my pronunciation is incorrect? Androgyne is also missing a tab, and seems to be acceptable. dictionary.com accepts the original pronunciation, as well as Oxford Languages, which powers Google's definitions.

**Comment by ns-studios** [comment]
Whoops! I broke the tab. Wow. I'm on a roll.
I thought the stress on masculine in transmasculine was not really there but it's not a biggy.

**Comment by Mohamed00** [comment]
Can you provide sources for androgyne?  Not entirely convinced the original is wrong.

**Comment by ns-studios** [comment]
[vid1](https://youtu.be/xkb6Y0UIBYk?t=64)
[vid2](https://youtu.be/G3YIacXTRTc?t=37)
[vid3](https://youtu.be/gHuw9mdl1eI?t=31)
Although, it does seem to be varying between andro gine (rhymes with wine), andro gene (rhymes with bean, and the variants above/the variant I went with. Totally your call, no hard feelings either way tbh.

**Comment by ns-studios** [comment]
Just realized that even my examples vary with the stress of drogin part. Lol. It's a crapshoot.

**Comment by Mohamed00** [comment]
Yeah, will probably not add that word, since it the original shows up in several sources, and in the case of ambiguous words like this, I lean towards leaving the original pronunciations alone. See doc/regressions.md.

**Comment by ns-studios** [comment]
Gotcha. No worries.

**Comment by Mohamed00** [comment]
Had to resolve some conflicts, but I added these entries. For future reference:
* Please modify both dictionary files, the Eloquence one in the root of this repository, and the ViaVoice TTS dictionary. If you don't have IBMTTS, that's fine, I'll tell you if something is pronounced correctly.
* Please provide sources for your entries. While I can do my own research on pronunciations, as I do with all contributions, it'll save time and headaches for everyone if sources are provided.
Note to self: I think it's about time I start using GitHub templates.

**Pull request closed without merging**
