### PR TITLE
1 word in main: ILC.

### PR DESCRIPTION
**Pull request by trypsynth**
### What are you correcting?

* The abbreviation ILC (Integrated Learning Center)

### What is your source for this pronunciation?

Its an abbreviation, so think it should be pretty straightforward. Related: Should we make a pull request template for abbreviations?

### CODE REVIEW

**Comment by Mohamed00** [comment]
@TheQuinbox This should be changed to use something like I LC instead. In its current form, it will be pronounced as Illinois C if abbreviation expansion is on. Also yeah, I'm considering making more templates, but will have to look in to how to make a template chooser.

**Comment by Mohamed00** [comment]
@TheQuinbox Actually, are you sure this is incorrect? I found a source that pronounces it the same way Eloquence/IBMTTS does. https://www.youtube.com/watch?v=bYEkdGH7tGE&t=38s

**Comment by Mohamed00** [comment]
@TheQuinbox And another source that also pronounces it the original way. https://www.youtube.com/watch?v=GNXohNCqHYM&t=33s

**Comment by Mohamed00** [comment]
And another. https://www.youtube.com/watch?v=8Dtbns_zmAQ&t=12s

**Comment by Mohamed00** [comment]
And yet another. https://www.youtube.com/watch?v=O3ivmiwe1-U&t=35

**Comment by trypsynth** [comment]
I'll be damned. I've never heard it said that way, but you are absolutely correct.

GitHub makes a chooser for you when doing it from the website (currently, we get a blank option, too). Same from the GitHub CLI which is how I do it.

**Comment by Mohamed00** [comment]
I'll look into it. I'm considering making issue and PR templates from removing words, but could consider it for other stuff as well.

**Pull request closed without merging**
